name: publish_image

on:
  workflow_dispatch:

jobs:
  publish_image:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push killbill/base:latest
        run: |
          TAG="killbill/stripe-demo:latest"
          DOCKER_BUILDKIT=1 docker build --no-cache -t $TAG -f Dockerfile .
          docker push $TAG
